### PR TITLE
fix standalone aar build

### PR DESCRIPTION
**Pull request by michaelknoch**
i was running into an ndk build issue when building the `aar` file with `./gradlew assemble`

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':MIDIDriver'.
> > No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

Updating the build tools and the gradle wrapper seem to fix the problem, but then we have to bump the minsdk to android sdk 21 (os version 5) because 12 is not supported by this toolchain

### CODE REVIEW

**Comment by shone** [comment]
The first commit, 'set min sdk to 23', appears to actually set the versions from 23 to 21. Then the next commit, 'fix standalone aar build', changes it back to 23. Could we re-do these commits, and also add commit message(s) about why the versions need to be changed?

**Comment by michaelknoch** [comment]
i rebased the two commits (sorry for the misleading message) into one commit. My recommendation would be to squash this pr into "devel" of this repository. @joshua-shone

**Comment by michaelknoch** [comment]
also added some more description to the pr, feel free to approve it if you think its ready @joshua-shone

**Comment by shone** [comment]
Thanks for the info, very helpful :) Could you put it into the commit message otherwise I don't think we'll see it yeah?

**Comment by michaelknoch** [comment]
done @joshua-shone

**Comment by shone** [comment]
Approved!

**Pull request merged**
